const ADD_TODO = "ADD_TODO";
const COMPLETE_TODO = "COMPLETE_TODO";
const UNCOMPLETE_TODO = "UNCOMPLETE_TODO";
const DELETE_TODO = "DELETE_TODO";

export { ADD_TODO, COMPLETE_TODO, UNCOMPLETE_TODO, DELETE_TODO };